### ISSUE TITLE
error in production:  Cannot assign to read only property 'state' of object '#'

### ISSUE THREAD

**Issue by samrjj32** [rpldy/react-uploady#473] opened 2023-02-14 05:20 UTC
error while uploading image files in production :
 Uncaught (in promise) TypeError: Cannot assign to read only property 'state' of object '#<Object>'

![upldy](https://user-images.githubusercontent.com/45480413/218646482-17d26715-4b14-4b4b-88a1-e1a78507135d.png)

**Comment by yoavniran** [comment] 2023-02-14 09:36
@samrjj32 Thanks for reporting but unfortunately I cannot do much with the little info you provided.
Please use the Bug Report template to provide all of the necessary information for me to investigate.
Most importantly, provide a reproducing code sample/sandbox

**Comment by yoavniran** [comment] 2023-02-23 11:29
closing for now. without repro cant proceed

**Closed by yoavniran** 2023-02-23 11:29 UTC
Labels: repro needed

**Comment by gerlv** [comment] 2023-11-18 21:01
I've run into the same error today. Still not 100% why it happened, but my guess it's this line - https://github.com/rpldy/react-uploady/blob/a32cf9f07ecc524938211774e2e9683ad4aed5f3/packages/core/shared/src/utils/devFreeze.js#L5

In the lifecycle hooks I was storing the whole object in the state, but since it was frozen, updating any part in the next hook update throws this error. Changing to keeping a copy of the object fixed the issue, i.e. instead of `= item;` to `= { ...item };`
